# Generated by Django 4.2.16 on 2026-04-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FID', models.CharField(max_length=20, unique=True)),
                ('kode', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=200)),
                ('jenjang', models.CharField(choices=[('S1', 'S1'), ('D3', 'D3'), ('D4', 'D4'), ('S2', 'S2'), ('S3', 'S3')], max_length=5)),
                ('fakultas', models.CharField(max_length=200)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prodi',
                'ordering': ['fakultas', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provinsi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.provinsi')),
            ],
            options={
                'db_table': 'kota',
                'ordering': ['nama'],
            },
        ),
    ]
