# Generated by Django 4.2.16 on 2026-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_universitas', models.CharField(default='Universitas Muhammadiyah Surakarta', max_length=200)),
                ('singkatan', models.CharField(default='UMS', max_length=20)),
                ('alamat', models.TextField(default='Jl. A. Yani Tromol Pos 1 Pabelan Kartasura')),
                ('kota', models.CharField(default='Surakarta', max_length=100)),
                ('kode_pos', models.CharField(blank=True, default='57102', max_length=10)),
                ('telepon', models.CharField(blank=True, default='(0271) 717417', max_length=50)),
                ('website', models.URLField(blank=True, default='https://www.ums.ac.id')),
                ('email_pmb', models.EmailField(blank=True, default='pmb@ums.ac.id', max_length=254)),
                ('nama_program', models.CharField(default='PMB Terpadu', max_length=200)),
                ('tahun_pmb', models.CharField(default='2026', max_length=10)),
                ('tahun_ajaran', models.CharField(default='2026/2027', max_length=20)),
                ('footer_copyright', models.CharField(blank=True, default='DSTI UMS', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo utama (untuk KTM, sertifikat)', null=True, upload_to='sitelogo/')),
                ('logo_kop', models.ImageField(blank=True, help_text='Logo kop surat / dokumen resmi', null=True, upload_to='sitelogo/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon browser (.ico/.png)', null=True, upload_to='sitelogo/')),
                ('nama_pimpinan', models.CharField(blank=True, default='', help_text='Nama rektor/pimpinan (untuk tanda tangan)', max_length=200)),
                ('nip_pimpinan', models.CharField(blank=True, default='', help_text='NIP / NIK pimpinan', max_length=50)),
                ('jabatan_pimpinan', models.CharField(blank=True, default='Rektor', help_text='Jabatan penandatangan', max_length=100)),
                ('kota_ttd', models.CharField(blank=True, default='Surakarta', help_text='Kota pada baris tanda tangan dokumen', max_length=100)),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
                'verbose_name_plural': 'Pengaturan Situs',
                'db_table': 'site_setting',
            },
        ),
    ]
