# Generated by Django 4.2.16 on 2026-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_login',
            field=models.ImageField(blank=True, help_text='Logo halaman login admin (versi gelap/terang sesuai tema)', null=True, upload_to='sitelogo/'),
        ),
    ]
