# Generated by Django 4.2.16 on 2026-04-23 10:02

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_logo_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon browser (.ico/.png)', null=True, upload_to='sitelogo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'svg']), core.validators.validate_favicon_size]),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo utama (untuk KTM, sertifikat)', null=True, upload_to='sitelogo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_kop',
            field=models.ImageField(blank=True, help_text='Logo kop surat / dokumen resmi', null=True, upload_to='sitelogo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_login',
            field=models.ImageField(blank=True, help_text='Logo halaman login admin (versi gelap/terang sesuai tema)', null=True, upload_to='sitelogo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
    ]
