# Generated by Django 4.2.16 on 2026-04-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesetting_favicon_alter_sitesetting_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaKuliahPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_pmb', models.CharField(help_text='Contoh: "2026" atau "2026/2027"', max_length=10, unique=True)),
                ('biaya_pendaftaran', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_pkkmb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('keterangan', models.TextField(blank=True, default='1. DPP (Dana Pengembangan dan Pembangunan) dapat dibayarkan 2 kali: pertama saat registrasi 50%, kedua sebelum UAS 50%.\n2. SPP (Sumbangan Pembinaan dan Pendidikan) dibayarkan tiap semester, 50% saat awal semester dan 50% sebelum UAS.\n3. Biaya daftar ulang akan dikembalikan 75% apabila calon mahasiswa undur diri karena diterima SNBP/SNBT, atau tidak lulus SLTA.\n4. Pembayaran registrasi sampai sebelum 1 Juli mendapat potongan 10% dari DPP, dan pembayaran tanggal 2 Juli–15 Agustus mendapat potongan 5% dari DPP.', help_text='Tampil di sertifikat lulus')),
                ('aktif', models.BooleanField(default=True, help_text='Periode yang dipakai untuk PMB saat ini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periode Biaya Kuliah',
                'verbose_name_plural': 'Periode Biaya Kuliah',
                'db_table': 'biaya_kuliah_periode',
                'ordering': ['-tahun_pmb'],
            },
        ),
        migrations.CreateModel(
            name='BiayaKuliahProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelas', models.CharField(choices=[('reguler', 'Reguler'), ('karyawan', 'Karyawan'), ('internasional', 'Internasional')], max_length=20)),
                ('dpp_cicilan_1', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='DPP Cicilan 1')),
                ('dpp_cicilan_2', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='DPP Cicilan 2')),
                ('spp_per_semester', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SPP / Semester')),
                ('biaya_saat_registrasi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Saat Registrasi')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.biayakuliahperiode')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prodi')),
            ],
            options={
                'verbose_name': 'Rincian Biaya Prodi',
                'verbose_name_plural': 'Rincian Biaya Prodi',
                'db_table': 'biaya_kuliah_prodi',
                'ordering': ['periode', 'jenis_kelas', 'prodi__fakultas', 'prodi__nama'],
                'unique_together': {('periode', 'prodi', 'jenis_kelas')},
            },
        ),
    ]
