# Generated by Django 4.2.16 on 2026-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_biayakuliahperiode_biayakuliahprodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayakuliahprodi',
            name='biaya_hidup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Hidup (boarding)'),
        ),
        migrations.AddField(
            model_name='biayakuliahprodi',
            name='dpp_spp_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='DPP & SPP Total (boarding)'),
        ),
        migrations.AddField(
            model_name='biayakuliahprodi',
            name='pengembangan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pengembangan (boarding)'),
        ),
        migrations.AlterField(
            model_name='biayakuliahperiode',
            name='keterangan',
            field=models.TextField(blank=True, default='1. DPP (Dana Pengembangan dan Pembangunan) dapat dibayarkan 2 kali: pertama saat regristrasi 50%; kedua sebelum UAS 50%.\n2. SPP (Sumbangan Pembinaan dan Pendidikan) per semester dibayarkan 2 kali, 50% saat awal semester dan 50% sebelum UAS.\n3. Biaya daftar ulang akan dikembalikan 75% apabila calon mahasiswa undur diri sebelum tanggal 8 Agustus 2026 karena diterima SNBP/SNBT, atau tidak lulus SLTA.\n4. Pembayaran regristrasi sampai sebelum 1 Juli 2026 mendapat potongan 10% dari DPP; dan pembayaran tanggal 2 Juli–8 Agustus 2026 mendapat potongan 5% dari DPP.', help_text='Tampil di sertifikat lulus'),
        ),
        migrations.AlterField(
            model_name='biayakuliahprodi',
            name='jenis_kelas',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('karyawan', 'Karyawan'), ('internasional', 'Internasional'), ('boarding', 'International Boarding')], max_length=20),
        ),
    ]
