# Generated by Django 4.2.16 on 2026-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prodi_kuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrasiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keuangan_aktif', models.BooleanField(default=True, help_text='Aktifkan pengiriman tagihan ke Sistem Keuangan.')),
                ('keuangan_api_base', models.URLField(blank=True, help_text='Base URL Sistem Keuangan, mis. https://keuangan.example.ac.id', max_length=300)),
                ('keuangan_ods_token', models.CharField(blank=True, help_text='X-API-Key inbound keuangan (ODS_INBOUND_TOKEN di sisi keuangan).', max_length=200)),
                ('keuangan_timeout', models.PositiveIntegerField(default=10, help_text='Timeout permintaan (detik).')),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Integrasi API',
                'verbose_name_plural': 'Konfigurasi Integrasi API',
                'db_table': 'integrasi_config',
            },
        ),
    ]
