# Generated by Django 4.2.16 on 2026-04-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeasiswaDaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_beasiswa', models.CharField(choices=[('BKAD', 'Beasiswa Khusus Anak Daerah'), ('BU-UMS', 'Beasiswa Unggulan UMS'), ('BTUMD', 'Beasiswa Tidak Mampu'), ('KIP', 'KIP Kuliah'), ('OSC', 'One Stop Community'), ('BP-ORS', 'Beasiswa Prestasi Olahraga/Seni'), ('BP-MTQ', 'Beasiswa Prestasi MTQ'), ('LAIN', 'Lainnya')], max_length=20)),
                ('batch', models.IntegerField(default=1)),
                ('status_seleksi', models.IntegerField(choices=[(0, 'Melengkapi Data'), (1, 'Proses Seleksi'), (2, 'Terverifikasi'), (3, 'Lolos'), (4, 'Tidak Lolos')], default=0)),
                ('file_formulir', models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/')),
                ('file_penghasilan', models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/')),
                ('file_rekomendasi', models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/')),
                ('file_raport', models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/')),
                ('file_prestasi', models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/')),
                ('file_toefl', models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/')),
                ('keterangan', models.TextField(blank=True)),
                ('catatan_panitia', models.TextField(blank=True)),
                ('diproses_oleh', models.CharField(blank=True, max_length=100)),
                ('tgl_diproses', models.DateTimeField(blank=True, null=True)),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beasiswa_daftar', to='pendaftaran.pendaftar')),
                ('prodi_lulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prodi')),
            ],
            options={
                'db_table': 'beasiswa_daftar',
            },
        ),
        migrations.CreateModel(
            name='BeasiswaPrestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('sekolah', 'Tingkat Sekolah'), ('kabkota', 'Tingkat Kab/Kota'), ('provinsi', 'Tingkat Provinsi'), ('nasional', 'Tingkat Nasional'), ('internasional', 'Tingkat Internasional')], max_length=15)),
                ('tahun', models.IntegerField()),
                ('file', models.FileField(upload_to='beasiswa/prestasi/')),
                ('beasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='beasiswa.beasiswadaftar')),
            ],
            options={
                'db_table': 'beasiswa_prestasi',
            },
        ),
    ]
