# Generated by Django 4.2.16 on 2026-04-23 10:02

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beasiswadaftar',
            name='file_formulir',
            field=models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='beasiswadaftar',
            name='file_penghasilan',
            field=models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='beasiswadaftar',
            name='file_prestasi',
            field=models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='beasiswadaftar',
            name='file_raport',
            field=models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='beasiswadaftar',
            name='file_rekomendasi',
            field=models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='beasiswadaftar',
            name='file_toefl',
            field=models.FileField(blank=True, null=True, upload_to='beasiswa/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='beasiswaprestasi',
            name='file',
            field=models.FileField(upload_to='beasiswa/prestasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
    ]
