# Generated by Django 4.2.16 on 2026-04-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaportBerkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_raport', models.FileField(blank=True, null=True, upload_to='raport/berkas/')),
                ('file_prestasi_1', models.FileField(blank=True, null=True, upload_to='raport/prestasi/')),
                ('file_prestasi_2', models.FileField(blank=True, null=True, upload_to='raport/prestasi/')),
                ('file_prestasi_3', models.FileField(blank=True, null=True, upload_to='raport/prestasi/')),
                ('tingkat_prestasi_1', models.CharField(blank=True, choices=[('sekolah', 'Tingkat Sekolah'), ('kabkota', 'Tingkat Kab/Kota'), ('provinsi', 'Tingkat Provinsi'), ('nasional', 'Tingkat Nasional'), ('internasional', 'Tingkat Internasional')], max_length=15)),
                ('tingkat_prestasi_2', models.CharField(blank=True, choices=[('sekolah', 'Tingkat Sekolah'), ('kabkota', 'Tingkat Kab/Kota'), ('provinsi', 'Tingkat Provinsi'), ('nasional', 'Tingkat Nasional'), ('internasional', 'Tingkat Internasional')], max_length=15)),
                ('tingkat_prestasi_3', models.CharField(blank=True, choices=[('sekolah', 'Tingkat Sekolah'), ('kabkota', 'Tingkat Kab/Kota'), ('provinsi', 'Tingkat Provinsi'), ('nasional', 'Tingkat Nasional'), ('internasional', 'Tingkat Internasional')], max_length=15)),
                ('nilai_raport', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nilai_prestasi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Belum Lengkap'), (1, 'Menunggu Validasi'), (2, 'Valid'), (3, 'Lulus'), (4, 'Tidak Lulus'), (5, 'Perbaikan'), (6, 'Undur Diri')], default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('diproses_oleh', models.CharField(blank=True, max_length=100)),
                ('tgl_diproses', models.DateTimeField(blank=True, null=True)),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raport_berkas', to='pendaftaran.pendaftar')),
                ('prodi_lulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prodi')),
            ],
            options={
                'db_table': 'raport_berkas',
            },
        ),
        migrations.CreateModel(
            name='RaportNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pendaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_raport', to='pendaftaran.pendaftar')),
            ],
            options={
                'db_table': 'raport_nilai',
                'unique_together': {('pendaftar', 'mata_pelajaran', 'semester')},
            },
        ),
    ]
