# Generated by Django 4.2.16 on 2026-04-23 10:02

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportberkas',
            name='file_prestasi_1',
            field=models.FileField(blank=True, null=True, upload_to='raport/prestasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='raportberkas',
            name='file_prestasi_2',
            field=models.FileField(blank=True, null=True, upload_to='raport/prestasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='raportberkas',
            name='file_prestasi_3',
            field=models.FileField(blank=True, null=True, upload_to='raport/prestasi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='raportberkas',
            name='file_raport',
            field=models.FileField(blank=True, null=True, upload_to='raport/berkas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
    ]
