# Generated by Django 4.2.16 on 2026-04-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_daftar', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=200)),
                ('NIK', models.CharField(max_length=16)),
                ('no_kk', models.CharField(blank=True, max_length=16)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], max_length=20)),
                ('no_hp', models.CharField(max_length=20)),
                ('no_telp_rumah', models.CharField(blank=True, max_length=20)),
                ('kode_negara', models.CharField(default='ID', max_length=5)),
                ('jalur', models.CharField(choices=[('raport', 'Jalur Raport'), ('beasiswa', 'Jalur Beasiswa'), ('umum', 'Jalur Umum')], max_length=10)),
                ('pas_foto', models.ImageField(blank=True, null=True, upload_to='foto/')),
                ('scan_ktp', models.FileField(blank=True, null=True, upload_to='ktp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prodi1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftar_prodi1', to='core.prodi')),
                ('prodi2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendaftar_prodi2', to='core.prodi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pendaftar',
            },
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jurusan', models.CharField(max_length=100)),
                ('nisn', models.CharField(blank=True, max_length=20)),
                ('akreditasi', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Belum', 'Belum Terakreditasi')], max_length=10)),
                ('tahun_lulus', models.IntegerField()),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.pendaftar')),
            ],
            options={
                'db_table': 'sekolah',
            },
        ),
        migrations.CreateModel(
            name='Ortu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('hubungan', models.CharField(choices=[('ayah', 'Ayah'), ('ibu', 'Ibu')], max_length=4)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('pendidikan', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA/SMK', 'SMA/SMK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10)),
                ('penghasilan', models.BigIntegerField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('pendaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortu', to='pendaftaran.pendaftar')),
            ],
            options={
                'db_table': 'ortu',
            },
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalan', models.TextField()),
                ('rt', models.CharField(blank=True, max_length=5)),
                ('rw', models.CharField(blank=True, max_length=5)),
                ('kelurahan', models.CharField(max_length=100)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kota')),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.pendaftar')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.provinsi')),
            ],
            options={
                'db_table': 'alamat',
            },
        ),
    ]
