# Generated by Django 4.2.16 on 2026-04-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Belum Daftar Ulang'), (1, 'Sudah Daftar Ulang'), (2, 'Batal / Undur Diri')], default=0)),
                ('tgl_registrasi', models.DateTimeField(blank=True, null=True)),
                ('nim', models.CharField(blank=True, help_text='NIM yang diberikan setelah daftar ulang', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('diproses_oleh', models.CharField(blank=True, max_length=100)),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrasi', to='pendaftaran.pendaftar')),
            ],
            options={
                'db_table': 'registrasi',
            },
        ),
    ]
