# Generated by Django 4.2.16 on 2026-04-23 10:02

import core.validators
import django.core.validators
from django.db import migrations, models
import pendaftaran.models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_registrasi_berkas_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='pas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='scan_ktp',
            field=models.FileField(blank=True, null=True, upload_to='ktp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='akte_lahir',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='bukti_bayar_pendaftaran',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='bukti_bayar_pengembangan',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='bukti_bayar_sks',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='hasil_tes_kesehatan',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='hasil_tes_mmpi2',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='kartu_keluarga',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='pas_foto',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='skhun',
            field=models.FileField(blank=True, null=True, upload_to=pendaftaran.models.upload_registrasi, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
    ]
