# Generated by Django 4.2.16 on 2026-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0004_alter_pendaftar_pas_foto_alter_pendaftar_scan_ktp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='kelas',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('karyawan', 'Karyawan'), ('internasional', 'Internasional')], default='reguler', help_text='Menentukan rincian biaya di sertifikat lulus', max_length=20),
        ),
    ]
