# Generated by Django 4.2.16 on 2026-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0006_alter_registrasi_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='kelas',
            field=models.CharField(blank=True, choices=[('reguler', 'Reguler'), ('karyawan', 'Karyawan'), ('internasional', 'Internasional'), ('boarding', 'International Boarding')], default='', help_text='Kelas pilihan cama. Sertifikat lulus baru bisa dicetak setelah kelas dipilih.', max_length=20),
        ),
    ]
