# Generated by Django 4.2.16 on 2026-06-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0010_registrasi_nomor_va'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='sumber_info_hp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='sumber_info',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('keluarga', 'Keluarga'), ('sekolah', 'Sekolah'), ('marketing', 'Marketing / Perekomendasi'), ('lainnya', 'Lainnya')], max_length=20),
        ),
    ]
