# Generated by Django 4.2.16 on 2026-04-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmumDaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Belum Lengkap'), (1, 'Menunggu Verifikasi'), (2, 'Lulus'), (3, 'Tidak Lulus')], default=0)),
                ('skor_cbt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('keterangan', models.TextField(blank=True)),
                ('diproses_oleh', models.CharField(blank=True, max_length=100)),
                ('tgl_diproses', models.DateTimeField(blank=True, null=True)),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umum_daftar', to='pendaftaran.pendaftar')),
                ('prodi_lulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prodi')),
            ],
            options={
                'db_table': 'umum_daftar',
            },
        ),
    ]
