upstream pmbbim {
    server 10.3.11.53:30084;
    keepalive 16;
}

server {
    listen 443 ssl;
    server_name pmb.bim.ac.id;

    ssl_certificate     /etc/letsencrypt/live/pmb.bim.ac.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pmb.bim.ac.id/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 64M;
    gzip on;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    location / {
        proxy_pass http://pmbbim;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}

server {
    listen 80;
    server_name pmb.bim.ac.id;
    return 301 https://pmb.bim.ac.id$request_uri;
}
